version: "3.7"
services:
  app:
    build:
      args:
        user: user
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: routing-project
    container_name: routing-project-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - routing-project

#  db:
#    image: mysql:5.7
#    container_name: routing-project-db
#    restart: unless-stopped
#    environment:
#      MYSQL_DATABASE: ${DB_DATABASE}
#      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
#      MYSQL_PASSWORD: ${DB_PASSWORD}
#      MYSQL_USER: ${DB_USERNAME}
#      SERVICE_TAGS: dev
#      SERVICE_NAME: mysql
#    volumes:
#      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
#    networks:
#      - routing-project

  nginx:
    image: nginx:alpine
    container_name: routing-test-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
#      - "443:443"
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - routing-project

networks:
  routing-project:
    driver: bridge
